apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: {{ .Release.Name }}-hcpvd-auth
spec:
  kubernetes:
    tokenExpirationSeconds: 600
    role: {{ .Values.vault.auhtRole }}
    serviceAccount: {{ .Release.Name }}-sa
  vaultConnectionRef: {{ .Release.Name }}-hcpvd-conn
  method: {{ .Values.vault.auth.method }}
  mount: {{ .Values.vault.auth.mount }}
  namespace: {{ .Values.vault.auth.namespace }}