apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: argo-vso-app-secrets
spec:
  destination:
    create: true
    name: argo-vso-app-secrets
    overwrite: false
  hmacSecretData: true
  mount: kvv2
  namespace: admin/tenant
  path: argo/app/content
  refreshAfter: 5s
  type: kv-v2
  vaultAuthRef: hcpvd-auth