apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: {{ .Release.Name }}-secrets
spec:
  destination:
    create: true
    name: {{ .Release.Name }}-secrets
    overwrite: false
  hmacSecretData: true
  mount: {{ .Values.vault.secret.mount }}
  namespace: {{ .Values.vault.secret.namespace }}
  path: {{ .Values.vault.secret.path }}
  refreshAfter: 5s
  type: kv-v2
  vaultAuthRef: {{ .Release.Name }}-hcpvd-auth